### ISSUE TITLE
목표 지표와 가드레일지표의 밸런스 - Case Study

### ISSUE THREAD

**Issue by hyejahaha** [CausalInferenceLab/OCE-Materials#7]
> **Problem**

실험을 진행할 때 성공 지표만 증가한다면 정말 이상적인 실험이겠지만, 슬프게도 많은 경우에 액션이 부정지표를 이끌어내는 경우가 종종 있다.
필자는 앞단의 사용자의 입력 항목 수 <> 지원 전환율의 밸런스부터 뒷단 실무 단계에서의 이탈률까지 다소 긴 퍼널을 살펴보는데 이 지표간의 관계는 언밸런스하다..!

- 예를 들어 랜딩페이지의 입력 항목이 늘어나면,
    → 랜딩페이지가 길어져 지원 전환율이 감소한다.
    →  실무단의 처리가 감소하여 뒷단 이탈은 감소, 최종 전환율은 개선된다.
    

이런 경우 주요 지표를 반영한 계산식으로 목표 지표를 설계하여 검증을 진행하지만, 모든 지표가 이상적으로 움직이지 않아 찜찜한 경우가 있다.
그러던 중 알라미 실험 아티클 시리즈를 읽게 되었고, 가설/실험의 설계 흐름과 끊임없는 고민에서 나오는 인사이트에 감탄하여 요약해보았다.

>**Case Study**

- 리텐션을 고려한 첫 구독 유도의 중요성 - 알라미 [(Link)](https://datarian.io/blog/how-to-increase-your-subscription-conversion-rate-while-maintaining-retention)
    - 실험안의 구독 전환율 증가, 리텐션 하락
        - 신규 유저 1% 증분의 가치 = Daily 신규 유저 * 1% * 광고 수익 LTV * 난이도 (실험의 타율)
        - 구독 전환율 1% 증분의 가치 = Daily 신규 유저 * 1% * 구독 LTV * 난이도 (실험의 타율)
            + 유저의 불쾌함 레벨 고려 (정성적)
            
    - 리텐션 이탈 원인 파악 → 후속 가설 분석 [(Link)](https://datarian.io/blog/finding-the-balance-between-subscriptions-and-retention)
        - 앱 설치 후 구독 유도 페이지가 먼저 나올 경우, 유료 기능만 있는 것으로 생각하고 즉시 이탈
        - 무료로 이용할 수 있음을 CTA로 제시 → 리텐션 유지 및 구독 전환율 증가
        - “불쾌함”을 가드레일로 정의

>**Lesson Learned**

- 난이도/불쾌함 등 실험에 영향을 주는 추가 요소들을 반영한 목표 지표 설계
- 목표지표와 부정지표를 적절히 수치화하여 비교
- 언제나 최선의 방안은 있다. 다각도로 분석하고 유저의 입장에서 가설을 잘! 세우고 끊임없이 실험하기

실험 분석 과정에 집요함이 부족했던 저 자신을 돌아보게되었네요! 내일 출근하면 미뤄뒀던 후속 가설 분석을 준비해봐야겠읍니다 :)
혹시 비슷한 경험이 있으시다면 공유 부탁드려요!

**Comment by jsshin2022** [comment]
좋은 사례 공유 및 스터디 자료에 힘써주셔서 감사합니다! @hyejahaha, @be-favorite  

저 또한 실무에서 실험이 부정적인 지표를 끌어내는 경우를 경험해서 간략하게 공유드려요.

- 목표 : 푸시 발송을 통한 유저 전환율 개선 (무엇에 대한 전환인지는 비밀입니다ㅎ)
    - Primary Index : 전환율
    - Guardrail Index : 앱삭제 (Bounce)
- 문제 : 푸시를 보냈더니, 전환을 시키려고 했던 유저들이 앱을 삭제하거나 푸시 수신을 동의하지 않도록 바꾸더라구요. 오히려, 푸시가 삭제/발송 차단에 대한 알림(?)이 되어버렸습니다. 
    - 유저 생각 : 아! 내가 이 앱을 아직 안지우고 있었구나 → 앱삭제
    
푸시에 대한 피로도가 존재(모서리해)하기 때문에, 유저 경험에도 부정적인 영향을 줄 수 있더라구요. 가드레일 지표를 높이지 않으면서, 유저 경험을 개선하기 위한 실험은 참 어렵다는 생각이 들었습니다. 

해결책으로 푸시에 대한 멘트를 바꾼다던가, 푸시 발송 시간을 조절해서 최대한 삭제율을 낮추려고 노력했던 기억이 있네요. 실험을 통해 꼭 성과내시길....!

**Comment by hyejahaha** [comment]
좋은 사례 공유 감사드립니다! @jsshin2022 

저도 마케팅 분야에 몸담고 있다보니, 푸시 메시지 실험을 진행한 경험이 있어 공유해주신 사례에 너무 공감합니다!!
비슷하게 요즘 SMS 메시지 테스트를 하고있는데 발송시마다 080수신거부 수가 늘어나는 부분이 고민이더라구요!

그래서 컨텐츠 부문에서 상당히 노력을 기울이고 있는 편입니다! 
획일화된 광고성 메시지를 담기보다는, 유저가 유용하게 느낄만한 정보를 담아 개인화 메시지를 기획하는 것이 정말 중요한 것 같아요!

단순 프로모션 홍보 메시지를 보내는 것 대신, "@@님! N번만 더 {전환}하면 ~혜택을 받을 수 있어요!" 의 개인화 문구를 발송했었는데
수신거부했던 분이 "친구는 이런 메시지를 받았는데, 저는 혜택 못받는건가요? 저도 메시지 보내주세요!" 라고 문의를 주신적이 있었습니다!

맨날 낮은 전환율과 수신거부율에 치이다가 저런 문의를 받으니 너무 짜릿했습니다ㅎㅎ
좋은 AB TEST 결과를 얻기위해서는, "고객 만족을 위한 문제정의" 전제조건이 필요하다는 본질을 다시금 깨닫는 경험이었어요!
